### ISSUE TITLE
Error when I start / reinstall the bot

### ISSUE THREAD

**Issue by MrAppleMania** [PokemonGoF/PokemonGo-Bot-Desktop#156]
When I login it directly shows this message. Would be glad if someone can help me! I also tried a fresh install of the PG Bot and it always said something about "check if you have the permissions/check if the repository still exists" :(
### Information
- OS X 10.10.5
  ![bildschirmfoto 2016-08-12 um 11 49 08](https://cloud.githubusercontent.com/assets/14994898/17618956/dba75016-6082-11e6-8a7a-6a511afb95d8.png)

**Comment by vincentcsm** [comment]
is it clean install or after pull?
encrypt.so and config file setup properly?

**Comment by clonn** [comment]
me too, i face same issue

**Comment by Outpox** [comment]
If you had an issue related to the bot when installing the app that's where the issue is.  
I think that you might be cloning the repo trough https and the deps are being loaded trough ssh. Could you please add an ssh key to your gitub account and clone the repos trough ssh?  
Or you could also go in the build folder, remove the `gofbot` folder if any and then `git clone https://github.com/PokemonGoF/PokemonGo-Bot/tree/d7cb7df27516b588252a767260176f92586489fa`

**Comment by MrAppleMania** [comment]
First I tried a re-clean install and it said I don't have the permission to access/repository doesn't exist. Then I just updated with pull gut and it always said that files will be overwritten and that's it. I googled it and then I had a solution I think it was "pull commit -(letter) git and it worked. Then I started it and it "crashed" after I logged in. Sry I'm new to this :(

**Comment by Outpox** [comment]
Then you should stick to the [builds](https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/releases). We're making big changes right now so the app will broke again.
