### ISSUE TITLE
preconfigured config.json file

### ISSUE THREAD

**Issue by KDA809** [PokemonGoF/PokemonGo-Bot-Desktop#222]
https://github.com/iiCe89/PokemonGo-bot-config i upload pre configured config.json file for anybody unsure when using pika-bot application i hope this helps - https://github.com/iiCe89/PokemonGo-bot-config

_Issue without proper information won't be answered_
### Information
- OS
- Git commit ( to get git commit run `git log -1 --format="%H"`)
- App's logs

**Comment by mrincredible2017** [comment]
Don't know if coincidence..... but since using your config.json I'm getting this in my log..

listLogs
12:22:58
Setting start location.

12:22:58
Coordinates found in passed in location, not geocoding.

12:22:58
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:22:58
Now at (34.0432108, -118.2675059, 0)

12:22:58
Login procedure started.

12:23:00
Login successful.

12:23:10
Starting bot...

12:23:12
Received level up reward: []

12:23:12
Next egg incubates in 0.54 km

12:23:29
Server is throttling, reconnecting in 30 seconds

12:23:59
Setting start location.

12:23:59
Coordinates found in passed in location, not geocoding.

12:23:59
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:23:59
Now at (34.0432108, -118.2675059, 0)

12:23:59
Login procedure started.

12:24:01
Login successful.

12:24:12
Starting bot...

12:24:13
Received level up reward: []

12:24:32
Server is throttling, reconnecting in 30 seconds

12:25:02
Setting start location.

12:25:02
Coordinates found in passed in location, not geocoding.

12:25:02
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:25:02
Now at (34.0432108, -118.2675059, 0)

12:25:02
Login procedure started.

12:25:03
Login successful.

12:25:13
Starting bot...

12:25:15
Received level up reward: []

12:25:34
Server is throttling, reconnecting in 30 seconds

12:26:04
Setting start location.

12:26:04
Coordinates found in passed in location, not geocoding.

12:26:04
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:26:04
Now at (34.0432108, -118.2675059, 0)

12:26:04
Login procedure started.

12:26:06
Login successful.

12:26:15
Starting bot...

12:26:17
Received level up reward: []

12:26:35
Server is throttling, reconnecting in 30 seconds

12:27:05
Setting start location.

12:27:05
Coordinates found in passed in location, not geocoding.

12:27:05
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:27:05
Now at (34.0432108, -118.2675059, 0)

12:27:05
Login procedure started.

12:27:07
Login successful.

12:27:16
Starting bot...

12:27:19
Received level up reward: []

12:27:35
Server is throttling, reconnecting in 30 seconds

12:28:05
Setting start location.

12:28:05
Coordinates found in passed in location, not geocoding.

12:28:05
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:28:05
Now at (34.0432108, -118.2675059, 0)

12:28:05
Login procedure started.

12:28:08
Login successful.

12:28:17
Starting bot...

12:28:19
Received level up reward: []

12:28:36
Server is throttling, reconnecting in 30 seconds

12:29:06
Setting start location.

12:29:06
Coordinates found in passed in location, not geocoding.

12:29:06
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:29:06
Now at (34.0432108, -118.2675059, 0)

12:29:06
Login procedure started.

12:29:08
Login successful.

12:29:18
Starting bot...

12:29:20
Received level up reward: []

12:29:38
Server is throttling, reconnecting in 30 seconds

12:30:08
Setting start location.

12:30:08
Coordinates found in passed in location, not geocoding.

12:30:08
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:30:08
Now at (34.0432108, -118.2675059, 0)

12:30:08
Login procedure started.

12:30:09
Login successful.

12:30:19
Starting bot...

12:30:21
Received level up reward: []

12:30:39
Server is throttling, reconnecting in 30 seconds

12:31:09
Setting start location.

12:31:09
Coordinates found in passed in location, not geocoding.

12:31:09
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:31:09
Now at (34.0432108, -118.2675059, 0)

12:31:09
Login procedure started.

12:31:11
Login successful.

12:31:22
Starting bot...

12:31:23
Received level up reward: []

12:31:42
Server is throttling, reconnecting in 30 seconds

12:32:12
Setting start location.

12:32:12
Coordinates found in passed in location, not geocoding.

12:32:12
Location found: 34.0432108, -118.2675059 (34.0432108, -118.2675059, 0.0)

12:32:12
Now at (34.0432108, -118.2675059, 0)

12:32:12
Login procedure started.

12:32:14
Login successful.

12:32:24
Starting bot...

12:32:26
Received level up reward: []

12:32:26
Next egg incubates in 0.54 km

**Comment by mrincredible2017** [comment]
Do you think it's a ban?

**Comment by KDA809** [comment]
seems to be working now :)

**Comment by mrincredible2017** [comment]
Can we get the config to do the following?
- Keep the highest IV pokemon when there are duplicates, but transfer this highest IV too if a higher IV pokemon is found (i.e keep transferring the lower IV pokemon if there is 1 or more, wherever possible). Isn't IV a better setting to be transferring as opposed to CP? I mean some Pokemon are low CP but high IV. And how does this work with regards to Magicarp too.. if we want to evolve to a Gyarados, Magicarps are always under 350 CP?

Also what is the current evolve setting based on? Under what conditions will it evolve the Pokemon? And what if there are duplicates? Is it evolving the best IV out of them all? How will it know WHEN to evolve? Maybe based on IV? 

Can we get the bot to Power Up based on candies etc?

**Comment by KDA809** [comment]
will work on Tommorow for you

**Comment by KDA809** [comment]
its just a balancing game because in order to clear pokemon you have to log into app it cant be done in game so this can cause pokémon to fill up super fast

**Comment by KDA809** [comment]
also any future issues post on my repo as i will get them faster as i get notified 👍

**Comment by Outpox** [comment]
@iiCe89 please notice the pen at the top right of your comments, that's an edit button.

**Comment by KDA809** [comment]
@Outpox apologies i was using Mobile app that didnt give me the option :)

**Comment by Outpox** [comment]
I know your pain, I switch to the desktop version on my phone since the mobile is limited in functionalities >.>
