### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by roshcamlian** [PokemonGoF/PokemonGo-Bot-Desktop#238]
We don't have the same config.json like PokemonGo-Bot? Tried using their whole config, error'd.

And or could we use their app instead? Their options look more complete compared to ours.

_Edit_

![pikabot](https://cloud.githubusercontent.com/assets/21103035/17956979/7a0180c8-6ac0-11e6-914d-4abe80ab0571.png)

**Comment by Outpox** [comment]
The 0.0.2 release is using an older version of the bot which might not be compatible with all the new options.

**Comment by roshcamlian** [comment]
yea I figured just really can't tell. so what do you suggest I do? or could I get a copy of all the working options please? or could ya teach me how to compare options you edit to the default options that do work. A library for those commands maybe? Idk where to find them or do them, I might edit stuff and make things worse @Outpox  :disappointed: 

_Edit: We shouldn't download anything from their repo right? That it might get mixed up with the application for the bot?_

**Comment by Outpox** [comment]
Unfortunatly I have no time to help you on that matter since we're focused on working on the new version of the app (which will feature those new options).  
The default config included should work as is. If you want to go deeper with the configuration I suggest you to use the [CLI bot](https://github.com/PokemonGoF/PokemonGo-Bot) and if you can't I won't have the time to help you neither. Altough there's an automated installer for Windows which does everything for you so you could have a look.  
If it still doesn't help you then I'm sorry but you will have to wait for a new release of the desktop app, and I have no release date to give you.
